name: wifimouni
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  file_picker: ^8.1.2
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.8

  # Localisation Flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  crypto: ^3.0.6
  local_auth: ^2.3.0
  share_plus: ^11.0.0
  cloud_functions: ^5.6.0
  app_links: ^6.4.1

  # Autres packages
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true