import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;
  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _values = <String, Map<String, String>>{
    'fr': {'appName': 'Wifi Mouni', 'login': 'Connexion', 'register': 'Créer un compte', 'email': 'Adresse e-mail', 'password': 'Mot de passe', 'emailRequired': 'Saisissez votre adresse e-mail.', 'emailInvalid': 'Saisissez une adresse e-mail valide.', 'passwordRequired': 'Saisissez votre mot de passe.', 'passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères.', 'continue': 'Continuer', 'settings': 'Paramètres', 'language': 'Langue', 'chooseLanguage': 'Choisir la langue', 'welcome': 'Bienvenue sur Wifi Mouni', 'home': 'Accueil', 'logout': 'Déconnexion', 'noAccount': 'Pas encore de compte ?', 'hasAccount': 'Vous avez déjà un compte ?', 'createAccount': 'Inscrivez-vous pour commencer', 'loginSubtitle': 'Connectez-vous à votre compte', 'loginFailed': 'E-mail ou mot de passe incorrect.', 'accountExists': 'Un compte existe déjà sur cet appareil.', 'pin': 'Code PIN', 'pinSubtitle': 'Protégez l’accès à vos réglages avec un code de 4 à 6 chiffres.', 'confirmPin': 'Confirmer le PIN', 'pinInvalid': 'Le PIN doit contenir 4 à 6 chiffres.', 'pinMismatch': 'Les deux PIN ne correspondent pas.', 'save': 'Enregistrer', 'removePin': 'Supprimer le PIN', 'pinSaved': 'PIN enregistré.', 'pinRemoved': 'PIN supprimé.', 'balance': 'Solde disponible', 'recharge': 'Recharger', 'rechargeSubtitle': 'Ajoutez un montant à votre portefeuille.', 'subscriptionPlans': 'Forfaits disponibles', 'plansUnavailable': 'Les forfaits sont temporairement indisponibles.', 'noPlans': 'Aucun forfait disponible.', 'customAmount': 'Recharge libre', 'amount': 'Montant', 'amountInvalid': 'Saisissez un montant valide.', 'amountRangeError': 'Le montant doit être compris entre {min} et {max}.', 'amountTooHigh': 'Le montant est trop élevé.', 'paymentMethod': 'Moyen de paiement', 'bankCard': 'Carte bancaire', 'mobileMoney': 'Mobile Money', 'bankTransfer': 'Virement bancaire', 'paymentRequired': 'Sélectionnez un moyen de paiement.', 'paymentMethodsUnavailable': 'Les moyens de paiement sont temporairement indisponibles.', 'noPaymentMethods': 'Aucun moyen de paiement disponible.', 'phoneNumber': 'Numéro', 'accountName': 'Nom du compte', 'exactAmount': 'Montant exact', 'transactionReference': 'Référence de transaction', 'referenceRequired': 'Saisissez la référence de transaction.', 'attachProof': 'Joindre une preuve de paiement', 'paymentMade': 'J’ai effectué le paiement', 'confirmRecharge': 'Confirmer la recharge', 'rechargeFailed': 'La recharge n’a pas pu être effectuée.', 'rechargeRequestSubmitted': 'Votre demande de recharge est en attente de vérification.', 'rechargeRequestFailed': 'La demande de recharge n’a pas pu être envoyée.', 'currency': 'XOF'},
    'en': {'appName': 'Wifi Mouni', 'login': 'Login', 'register': 'Create account', 'email': 'Email address', 'password': 'Password', 'emailRequired': 'Enter your email address.', 'emailInvalid': 'Enter a valid email address.', 'passwordRequired': 'Enter your password.', 'passwordTooShort': 'Password must be at least 6 characters.', 'continue': 'Continue', 'settings': 'Settings', 'language': 'Language', 'chooseLanguage': 'Choose language', 'welcome': 'Welcome to Wifi Mouni', 'home': 'Home', 'logout': 'Log out', 'noAccount': "Don't have an account?", 'hasAccount': 'Already have an account?', 'createAccount': 'Sign up to get started', 'loginSubtitle': 'Log in to your account', 'loginFailed': 'Incorrect email or password.', 'accountExists': 'An account already exists on this device.', 'pin': 'PIN', 'pinSubtitle': 'Protect access to your settings with a 4 to 6 digit PIN.', 'confirmPin': 'Confirm PIN', 'pinInvalid': 'The PIN must contain 4 to 6 digits.', 'pinMismatch': 'The PINs do not match.', 'save': 'Save', 'removePin': 'Remove PIN', 'pinSaved': 'PIN saved.', 'pinRemoved': 'PIN removed.', 'balance': 'Available balance', 'recharge': 'Top up', 'rechargeSubtitle': 'Add an amount to your wallet.', 'subscriptionPlans': 'Available plans', 'plansUnavailable': 'Plans are temporarily unavailable.', 'noPlans': 'No plans available.', 'customAmount': 'Custom top-up', 'amount': 'Amount', 'amountInvalid': 'Enter a valid amount.', 'amountRangeError': 'The amount must be between {min} and {max}.', 'amountTooHigh': 'The amount is too high.', 'paymentMethod': 'Payment method', 'bankCard': 'Bank card', 'mobileMoney': 'Mobile Money', 'bankTransfer': 'Bank transfer', 'paymentRequired': 'Select a payment method.', 'paymentMethodsUnavailable': 'Payment methods are temporarily unavailable.', 'noPaymentMethods': 'No payment methods available.', 'phoneNumber': 'Phone number', 'accountName': 'Account name', 'exactAmount': 'Exact amount', 'transactionReference': 'Transaction reference', 'referenceRequired': 'Enter the transaction reference.', 'attachProof': 'Attach payment proof', 'paymentMade': 'I have made the payment', 'confirmRecharge': 'Confirm top up', 'rechargeFailed': 'The top up could not be completed.', 'rechargeRequestSubmitted': 'Your top-up request is pending verification.', 'rechargeRequestFailed': 'The top-up request could not be submitted.', 'currency': 'XOF'},
    'es': {'login': 'Iniciar sesión', 'register': 'Crear cuenta', 'email': 'Correo electrónico', 'password': 'Contraseña', 'continue': 'Continuar', 'settings': 'Ajustes', 'language': 'Idioma', 'chooseLanguage': 'Elegir idioma', 'welcome': 'Bienvenido a Wifi Mouni', 'home': 'Inicio', 'logout': 'Cerrar sesión', 'noAccount': '¿No tienes una cuenta?', 'hasAccount': '¿Ya tienes una cuenta?', 'createAccount': 'Regístrate para comenzar', 'loginSubtitle': 'Inicia sesión en tu cuenta'},
    'ar': {'login': 'تسجيل الدخول', 'register': 'إنشاء حساب', 'email': 'البريد الإلكتروني', 'password': 'كلمة المرور', 'continue': 'متابعة', 'settings': 'الإعدادات', 'language': 'اللغة', 'chooseLanguage': 'اختر اللغة', 'welcome': 'مرحبًا بك في Wifi Mouni', 'home': 'الرئيسية', 'logout': 'تسجيل الخروج', 'noAccount': 'ليس لديك حساب؟', 'hasAccount': 'لديك حساب بالفعل؟', 'createAccount': 'أنشئ حسابًا للبدء', 'loginSubtitle': 'سجّل الدخول إلى حسابك'},
    'pt': {'login': 'Entrar', 'register': 'Criar conta', 'email': 'E-mail', 'password': 'Senha', 'continue': 'Continuar', 'settings': 'Definições', 'language': 'Idioma', 'chooseLanguage': 'Escolher idioma', 'welcome': 'Bem-vindo ao Wifi Mouni', 'home': 'Início', 'logout': 'Sair', 'noAccount': 'Ainda não tem uma conta?', 'hasAccount': 'Já tem uma conta?', 'createAccount': 'Crie uma conta para começar', 'loginSubtitle': 'Entre na sua conta'},
    'hi': {'login': 'लॉग इन', 'register': 'खाता बनाएँ', 'email': 'ईमेल पता', 'password': 'पासवर्ड', 'continue': 'जारी रखें', 'settings': 'सेटिंग्स', 'language': 'भाषा', 'chooseLanguage': 'भाषा चुनें', 'welcome': 'Wifi Mouni में आपका स्वागत है', 'home': 'होम', 'logout': 'लॉग आउट', 'noAccount': 'खाता नहीं है?', 'hasAccount': 'पहले से खाता है?', 'createAccount': 'शुरू करने के लिए साइन अप करें', 'loginSubtitle': 'अपने खाते में लॉग इन करें'},
    'de': {'login': 'Anmelden', 'register': 'Konto erstellen', 'email': 'E-Mail-Adresse', 'password': 'Passwort', 'continue': 'Weiter', 'settings': 'Einstellungen', 'language': 'Sprache', 'chooseLanguage': 'Sprache auswählen', 'welcome': 'Willkommen bei Wifi Mouni', 'home': 'Startseite', 'logout': 'Abmelden', 'noAccount': 'Noch kein Konto?', 'hasAccount': 'Bereits ein Konto?', 'createAccount': 'Jetzt registrieren', 'loginSubtitle': 'Melde dich bei deinem Konto an'},
    'ja': {'login': 'ログイン', 'register': 'アカウント作成', 'email': 'メールアドレス', 'password': 'パスワード', 'continue': '続ける', 'settings': '設定', 'language': '言語', 'chooseLanguage': '言語を選択', 'welcome': 'Wifi Mouniへようこそ', 'home': 'ホーム', 'logout': 'ログアウト', 'noAccount': 'アカウントをお持ちでないですか？', 'hasAccount': 'すでにアカウントをお持ちですか？', 'createAccount': '登録して始める', 'loginSubtitle': 'アカウントにログイン'},
    'ru': {'login': 'Войти', 'register': 'Создать аккаунт', 'email': 'Электронная почта', 'password': 'Пароль', 'continue': 'Продолжить', 'settings': 'Настройки', 'language': 'Язык', 'chooseLanguage': 'Выберите язык', 'welcome': 'Добро пожаловать в Wifi Mouni', 'home': 'Главная', 'logout': 'Выйти', 'noAccount': 'Нет аккаунта?', 'hasAccount': 'Уже есть аккаунт?', 'createAccount': 'Зарегистрируйтесь, чтобы начать', 'loginSubtitle': 'Войдите в свой аккаунт'},
    'zh': {'login': '登录', 'register': '创建账户', 'email': '电子邮箱', 'password': '密码', 'continue': '继续', 'settings': '设置', 'language': '语言', 'chooseLanguage': '选择语言', 'welcome': '欢迎使用 Wifi Mouni', 'home': '首页', 'logout': '退出登录', 'noAccount': '还没有账户？', 'hasAccount': '已有账户？', 'createAccount': '注册后开始使用', 'loginSubtitle': '登录您的账户'},
    'it': {'appName': 'Wifi Mouni', 'login': 'Accedi', 'register': 'Crea account', 'email': 'Indirizzo email', 'password': 'Password', 'emailRequired': 'Inserisci il tuo indirizzo email.', 'emailInvalid': 'Inserisci un indirizzo email valido.', 'passwordRequired': 'Inserisci la password.', 'passwordTooShort': 'La password deve contenere almeno 6 caratteri.', 'continue': 'Continua', 'settings': 'Impostazioni', 'language': 'Lingua', 'chooseLanguage': 'Scegli la lingua', 'welcome': 'Benvenuto su Wifi Mouni', 'home': 'Home', 'logout': 'Esci', 'noAccount': 'Non hai ancora un account?', 'hasAccount': 'Hai già un account?', 'createAccount': 'Registrati per iniziare', 'loginSubtitle': 'Accedi al tuo account', 'loginFailed': 'Email o password non corretti.', 'accountExists': 'Esiste già un account su questo dispositivo.', 'pin': 'PIN', 'pinSubtitle': "Proteggi l'accesso alle impostazioni con un PIN da 4 a 6 cifre.", 'confirmPin': 'Conferma PIN', 'pinInvalid': 'Il PIN deve contenere da 4 a 6 cifre.', 'pinMismatch': 'I PIN non corrispondono.', 'save': 'Salva', 'removePin': 'Rimuovi PIN', 'pinSaved': 'PIN salvato.', 'pinRemoved': 'PIN rimosso.'},
    'tr': {'appName': 'Wifi Mouni', 'login': 'Giriş yap', 'register': 'Hesap oluştur', 'email': 'E-posta adresi', 'password': 'Şifre', 'emailRequired': 'E-posta adresinizi girin.', 'emailInvalid': 'Geçerli bir e-posta adresi girin.', 'passwordRequired': 'Şifrenizi girin.', 'passwordTooShort': 'Şifre en az 6 karakter olmalıdır.', 'continue': 'Devam', 'settings': 'Ayarlar', 'language': 'Dil', 'chooseLanguage': 'Dil seçin', 'welcome': "Wifi Mouni'ye hoş geldiniz", 'home': 'Ana sayfa', 'logout': 'Çıkış yap', 'noAccount': 'Henüz hesabınız yok mu?', 'hasAccount': 'Zaten hesabınız var mı?', 'createAccount': 'Başlamak için kaydolun', 'loginSubtitle': 'Hesabınıza giriş yapın', 'loginFailed': 'E-posta veya şifre hatalı.', 'accountExists': 'Bu cihazda zaten bir hesap var.', 'pin': 'PIN', 'pinSubtitle': 'Ayarlarınıza erişimi 4 ila 6 haneli PIN ile koruyun.', 'confirmPin': "PIN'i onayla", 'pinInvalid': 'PIN 4 ila 6 haneli olmalıdır.', 'pinMismatch': "PIN'ler eşleşmiyor.", 'save': 'Kaydet', 'removePin': "PIN'i kaldır", 'pinSaved': 'PIN kaydedildi.', 'pinRemoved': 'PIN kaldırıldı.'},
    'ko': {'appName': 'Wifi Mouni', 'login': '로그인', 'register': '계정 만들기', 'email': '이메일 주소', 'password': '비밀번호', 'emailRequired': '이메일 주소를 입력하세요.', 'emailInvalid': '올바른 이메일 주소를 입력하세요.', 'passwordRequired': '비밀번호를 입력하세요.', 'passwordTooShort': '비밀번호는 6자 이상이어야 합니다.', 'continue': '계속', 'settings': '설정', 'language': '언어', 'chooseLanguage': '언어 선택', 'welcome': 'Wifi Mouni에 오신 것을 환영합니다', 'home': '홈', 'logout': '로그아웃', 'noAccount': '계정이 없으신가요?', 'hasAccount': '이미 계정이 있으신가요?', 'createAccount': '시작하려면 가입하세요', 'loginSubtitle': '계정에 로그인하세요', 'loginFailed': '이메일 또는 비밀번호가 올바르지 않습니다.', 'accountExists': '이 기기에 이미 계정이 있습니다.', 'pin': 'PIN', 'pinSubtitle': '4~6자리 PIN으로 설정에 대한 접근을 보호하세요.', 'confirmPin': 'PIN 확인', 'pinInvalid': 'PIN은 4~6자리여야 합니다.', 'pinMismatch': 'PIN이 일치하지 않습니다.', 'save': '저장', 'removePin': 'PIN 삭제', 'pinSaved': 'PIN이 저장되었습니다.', 'pinRemoved': 'PIN이 삭제되었습니다.'},
    'nl': {'appName': 'Wifi Mouni', 'login': 'Inloggen', 'register': 'Account aanmaken', 'email': 'E-mailadres', 'password': 'Wachtwoord', 'emailRequired': 'Voer je e-mailadres in.', 'emailInvalid': 'Voer een geldig e-mailadres in.', 'passwordRequired': 'Voer je wachtwoord in.', 'passwordTooShort': 'Het wachtwoord moet minstens 6 tekens bevatten.', 'continue': 'Doorgaan', 'settings': 'Instellingen', 'language': 'Taal', 'chooseLanguage': 'Kies een taal', 'welcome': 'Welkom bij Wifi Mouni', 'home': 'Home', 'logout': 'Uitloggen', 'noAccount': 'Nog geen account?', 'hasAccount': 'Heb je al een account?', 'createAccount': 'Meld je aan om te beginnen', 'loginSubtitle': 'Log in op je account', 'loginFailed': 'Onjuist e-mailadres of wachtwoord.', 'accountExists': 'Er bestaat al een account op dit apparaat.', 'pin': 'PIN', 'pinSubtitle': 'Bescherm de toegang tot je instellingen met een PIN van 4 tot 6 cijfers.', 'confirmPin': 'PIN bevestigen', 'pinInvalid': 'De PIN moet 4 tot 6 cijfers bevatten.', 'pinMismatch': "De PIN's komen niet overeen.", 'save': 'Opslaan', 'removePin': 'PIN verwijderen', 'pinSaved': 'PIN opgeslagen.', 'pinRemoved': 'PIN verwijderd.'},
  };

  String text(String key) => _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations._values.keys.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}